### ISSUE TITLE
realizeAmount brackets serve no purpose

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#10]
(line 500)
uint256 realizeAmout = (liquidateAmount * discountRate) / 100;
the brackets serve no purpose 
-> 
uint256 realizeAmout = liquidateAmount * discountRate / 100;

if you want to show where the brackets originally came from you can use: 
uint256 realizeAmout = liquidateAmount * (discountRate / 100);

**Comment by Morteza3123** [comment]
Solved.
