### ISSUE TITLE
totalInvestedValue: is it reduced when an order is closed but unfilled?

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#11]
line 261
  function openLongOrderUsd()
This function adds to the TotalInvestedValue 

But if a user closes their order before the order is filled, or upon only partial fill. Is the TotalInvestedValue reduced?

**Comment by Morteza3123** [comment]
TotalInvestedValue is changed only for opening or closing the positions not for opening/cancelling of orders. when two order matches in the same price we change the TotalInvestedValue.

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/e88a1cabd055488e39b856cb57ddb5c43e7a8c4d/contracts/Exchange.sol#L289-L312

**Comment by Waltermelon-lang** [comment]
Perfect
