### ISSUE TITLE
typo function name  function _closeLongPostito

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#12]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/d07cf743027b1330c22411620f3d1ddf1c741598/contracts/Exchange.sol#L240
 function _closeLongPostito ->
function _closeLongPostition

typo

**Comment by Morteza3123** [comment]
True

**Comment by Waltermelon-lang** [comment]
I made a typo, apologies.
_closeLongPostiton ->
_closeLongPosition

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c7b8a4164694afa61cabd8f3e642e94c8fc30a5e/contracts/Exchange.sol#L275
