### ISSUE TITLE
public function?

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#13]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/d07cf743027b1330c22411620f3d1ddf1c741598/contracts/Exchange.sol#L87

Should adding and removing users be a public function?

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/47b955ca01b45cd3d790ecfabb387d83277ca011/contracts/Exchange.sol#L89

Yes, it should be internal

**Comment by Waltermelon-lang** [comment]
;)
