### ISSUE TITLE
usd to vUsd

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#15]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/d07cf743027b1330c22411620f3d1ddf1c741598/contracts/Exchange.sol#L166

  function getLongUsdAmountOut(uint256 _vBaycAmount) public view returns (uint256) {
  }
  function getShortUsdAmountOut(uint256 _vBaycAmount) public view returns (uint256) 
  }

I prefer getLongVusdAmountOut, getShortVusdAmountOut

**Comment by Morteza3123** [comment]
Right.
