### ISSUE TITLE
liquiding users every time a trade is submitted

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#16]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/d07cf743027b1330c22411620f3d1ddf1c741598/contracts/Exchange.sol#L206

Do you agree that liquidating users every time somebody wants to trade is a viable idea?

**Comment by Morteza3123** [comment]
When a user trade, the price changes. So by each trade we can run the liquidation functions. It does not take significant gas (maybe one or two users get liquidated in that price)

**Comment by Waltermelon-lang** [comment]
We are letting the liquidations go first at the moment. 
However, the liquidation functions are run on the premise of the old/current price, which should not liquidate them, 
so the function will do nothing.
For example, let's say we have one long position and one short position. 
The longer can liquidate the shorter by buying a huge amount. The transaction would go first since the liquidation would not happen based on the old price. 
So I suggest to run the     
liquidateUsers();
partialLiquidateUsers();
on the premise of the new price by plugging in: _assetSize and calculating the new price. (might need a new function for that)

Furthermore, I suggest disabling transactions that move the pool away (in the wrong direction) of the oracle price by more than f.e. 10%.

Example price 10, oracle price 13. Diff = (13-10)/10 * 100 = 30% 
Suggested new price 11 after transaction: (13-10.5/10.5) = 23.8% (allowed)
Suggested new price 9 after transaction: (13-9/9) = 44% (not allowed)
Suggested new price 20 after transaction: (13-20/20) = -35% (too much, not allowed, needs to stay within (-10%,10%) of oracle.

Example:
max_range = mr = 10
//current diff = cd (example 30% see above)
// current diff distance = cdd =  abs(cd) - mr  (20%)
// diff after suggest trade = sd (23.8%, example see above)
// suggested diff distance = sdd = abs(sd) - 10  (13.8%)
   
 if ( cdd>0):
    //we are outside the target range and need to be brought back
     if ((cdd - sdd) > 0): 
         trade allowed, we move closer
else:
    //we are inside the target range
    if (sdd < 10):
         //trade allowed we stay within target range.

Then we can update the oracle price more than every hour (without running the fundingrate function) so the pool will stay aware of the target price and is allowed to trade accordingly.

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c7b8a4164694afa61cabd8f3e642e94c8fc30a5e/contracts/Exchange.sol#L243-L255

First In the function we check the price will not move alot after that we liquidate users by new price.

**Comment by Waltermelon-lang** [comment]
Big one, great work!
