### ISSUE TITLE
minus minus can be just plus

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#17]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/d07cf743027b1330c22411620f3d1ddf1c741598/contracts/Exchange.sol#L346

the vUSD of the bored ape is positive, thus the vUSD value the user was holding is negative
so f.e. 4000 + (-3000) = 1000

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/47b955ca01b45cd3d790ecfabb387d83277ca011/contracts/Exchange.sol#L360

Yes its +, I wanted to show it simple to understand. But finally it should be positive
