### ISSUE TITLE
using the oracle to adjust the virtual pool price

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#18]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/d07cf743027b1330c22411620f3d1ddf1c741598/contracts/Exchange.sol#L483

I suggest to not use the oracle to adjust the virtual pool price. 
An example, say we have only one user, Bob, he buys and the price goes up, then he sells and the price moves down back to where it started.
He cannot make a profit but he can open a position, This is important because somebody needs to be the first to open a position.
Only when the pool price moves outside of bobs own trading actions can he make a profit or loss. (f.e. because of Alice buys after Bob)

If we would adjust the pool price according to the oracle price, Bob can make a profit that is not covered by other people their losses. We do not take on exposure to people and their trades, so this is impossible.

My solution: the collateral balance of the long and short holders gets exposed to these price changes. If bob is the only long, he gets money from nobody (cause there are no shorters) and thus he gets nothing. The price of the pool is not touched.

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/47b955ca01b45cd3d790ecfabb387d83277ca011/contracts/Exchange.sol#L523-L528

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/47b955ca01b45cd3d790ecfabb387d83277ca011/contracts/Exchange.sol#L531

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/47b955ca01b45cd3d790ecfabb387d83277ca011/contracts/Exchange.sol#L539

I added the condition that if one side doesn't exist, the funding function will not run. Also, the funding fee will be according to the real trader's assetSize. For example, if index price is more than oracle price, we calculate the funding fee according to the all active short asset size and change the price to give this reward to long users(by decrease the vusd pool and decreasing the vBayc pool (by fixed k)

**Comment by Waltermelon-lang** [comment]
I not sure about the following: 
If I open a long worth $10K and after me a short opens for $1K, 
so now the pool price is allowed to move according to the funding rate. 
Lets say the pool moves up 10% in price, so now the long is at a $11K, and the short is down to $900, so 100$ loss versus $1K profit. 
This is not possible since the losses needs to cancel out the profits. 
If we say, well then the short goes to zero, then they cancel out, but that would mean the short is suddenly 10x leveraged because the long position size was bigger.

Therefore, I think it is not possible not move the pool price (unless long and short are exactly the same size).
Another idea therefore might be: charge users the fundFee so they are incentivised to move the pool. 
However, whenever they want to exit or get liquididated they are also charged their part of the fundFee,
so that if we have 10K users, they are all billed for 1/10.000 (1/activeUsers.length)  gas fee per fundrate round .

**Comment by Morteza3123** [comment]
In current code, I always calculate the fund fee by loser's position size.

By your example. Long worth 10K and short worth 1K. 
If funding rate is +10%(indexPrice > oraclePrice), So funding fee will be calculte according to the worth of short positions (fundingFee = 10%*1K= 100);

If funding rate is -10%(indexPrice < oraclePrice), So funding fee will be calculte according to the worth of long positions (fundingFee = 10%*10K= 1000);

So always, funding fee will be according to the loser asset size.
If we have 1000K long and only 1K short and funding rate is positive, losers are long users and the funding fee is based on long user's asset size. If funding rate is negative, losers are short users and funding fee is based on short user's asset size. So funding fee is always based on the loser assetSize(1000K-10%*1000K or 1K - 10%1K)

**Comment by Waltermelon-lang** [comment]
"In current code, I always calculate the fund fee by loser's position size."
Good to know and I do not want to calculate the funding fee like this, it has to be relative to people their position size and just as an incentive without actually moving the pool price. 
You can't touch the pool price (unless you can convince me otherwise), cause it can create net positive/negative profit and this is a zero sum game.

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c7b8a4164694afa61cabd8f3e642e94c8fc30a5e/contracts/Exchange.sol#L844-L882


I edited the function, so each user will have the funding fee effect in the collateral.

**Comment by Waltermelon-lang** [comment]
💯
