### ISSUE TITLE
trading fee

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#19]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/d07cf743027b1330c22411620f3d1ddf1c741598/contracts/Exchange.sol#L216

Can you charge the trading fee on the vUsd size from the users collateral to an address controlled by NexLabs (f.e. the onlyOwner address, but let me know what you thing is smart) for every trade made (except perhaps liquidation sale)

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/47b955ca01b45cd3d790ecfabb387d83277ca011/contracts/Exchange.sol#L225-L229

**Comment by Waltermelon-lang** [comment]
great, done!
