### ISSUE TITLE
swap fee condition

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#20]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/d07cf743027b1330c22411620f3d1ddf1c741598/contracts/Exchange.sol#L119

Perhaps add a condition so that we cannot change the fee to fast and put it too high.
Lets say max 5%, min 0.01%, 12hr timelock might be interesting etc, maybe max change from previous number by say absolute 1%.

I we could change this too fast, we could hold user collateral hostage, this would be a problem if the onlyOwner address get hacked.

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/47b955ca01b45cd3d790ecfabb387d83277ca011/contracts/Exchange.sol#L39-L40

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/47b955ca01b45cd3d790ecfabb387d83277ca011/contracts/Exchange.sol#L120-L127

**Comment by Waltermelon-lang** [comment]
Im loving it!
