### ISSUE TITLE
pnl reset to zero

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#21]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/d07cf743027b1330c22411620f3d1ddf1c741598/contracts/Exchange.sol#L307

If we change the collateral with the (unrealized) pnl, we need to set the pnl to zero. (unless we close the position and throw away all the storage that comes with it?) 

Can you change this for every instance where the collateral is changed with the pnl?

**Comment by Morteza3123** [comment]
PNL is not a global variable. pnl is distance between vusd balance and bayc value.
uint256 pnl = usdBaycValue - uint256(positive(userPartialvUsdBalance));

if we close the position also we change the vBayc and cUsd balance of the user so the pnl automatically will be zero (for complete close position ) or getting to near to the zero for partial closing.

**Comment by Waltermelon-lang** [comment]
Perfect!
