### ISSUE TITLE
substract loss

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#22]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c7b8a4164694afa61cabd8f3e642e94c8fc30a5e/contracts/Exchange.sol#L466

should be + no? 
In that case no if statement needed perhaps

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/cb6c67b801a4c8f2187d44484a724bdda15d17ed/contracts/Exchange.sol#L469
