### ISSUE TITLE
Same + issue

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#23]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c7b8a4164694afa61cabd8f3e642e94c8fc30a5e/contracts/Exchange.sol#L466

Also here I think should be + sign and no need for if statement similar to previous issue.

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/cb6c67b801a4c8f2187d44484a724bdda15d17ed/contracts/Exchange.sol#L469

In new change pnl is added to the collateral (int can be positive or negative)

**Comment by Waltermelon-lang** [comment]
👍
