### ISSUE TITLE
flip equation?

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#24]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c7b8a4164694afa61cabd8f3e642e94c8fc30a5e/contracts/Exchange.sol#L899

Example:
Oracle price is 100ETH/per APE right
So 1000USDC/100APES = 10$ per APE

Flip the nominator with the denominator? for currentPrice &  newPrice

**Comment by Morteza3123** [comment]
Oracle has usd price too.

<img width="586" alt="image" src="https://user-images.githubusercontent.com/80649310/195353116-47d53de8-f1aa-49cf-8a99-9d4700d685ff.png">

**Comment by Waltermelon-lang** [comment]
See my other reply

**Comment by Morteza3123** [comment]
I got it. 

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/8347102a56aa17d097d5806c36100af0f0f5e430/contracts/Exchange.sol#L862

**Comment by Morteza3123** [comment]
I got it. 

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/8347102a56aa17d097d5806c36100af0f0f5e430/contracts/Exchange.sol#L862
