### ISSUE TITLE
Difference

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#25]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c7b8a4164694afa61cabd8f3e642e94c8fc30a5e/contracts/Exchange.sol#L903

Probably all instance of:
Different -> Difference

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/cb6c67b801a4c8f2187d44484a724bdda15d17ed/contracts/Exchange.sol#L936

**Comment by Waltermelon-lang** [comment]
I could still find 7 instances of Different, all 7 can go to Difference

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/8347102a56aa17d097d5806c36100af0f0f5e430/contracts/Exchange.sol#L936

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/8347102a56aa17d097d5806c36100af0f0f5e430/contracts/Exchange.sol#L936
