### ISSUE TITLE
flip equation

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#26]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c7b8a4164694afa61cabd8f3e642e94c8fc30a5e/contracts/Exchange.sol#L845
Again here probably flip the equation $ per APE = dollar amount / APE amount.

**Comment by Morteza3123** [comment]
Oracle has both ETH and USD for price

https://market.link/nodes/NFTBank/integrations

<img width="580" alt="image" src="https://user-images.githubusercontent.com/80649310/195352540-d18ce105-9149-4bcb-a6fb-aa9df4b30f70.png">

**Comment by Waltermelon-lang** [comment]
Yeah but that does not change the notion that is in ETH/APE or USD/APE not APE/USD or APE/ETH. 
So the units need to match. ->  vBaycPoolSize / vUsdPoolSize;  = APE/USD

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/8347102a56aa17d097d5806c36100af0f0f5e430/contracts/Exchange.sol#L862

**Comment by Waltermelon-lang** [comment]
This is another occurence: 
Line 932:    uint256 currentPrice = vBaycPoolSize / vUsdPoolSize;
can you also change all indexPrice -> currentPrice 
for consistency of function names

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/5bcffba4faa11376b4b01c2875af207113015b6c/contracts/Exchange.sol#L862

**Comment by Waltermelon-lang** [comment]
nice, I see you also did
SafeERC20.safeTransfer(IERC20...
