### ISSUE TITLE
brackets

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#27]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c7b8a4164694afa61cabd8f3e642e94c8fc30a5e/contracts/Exchange.sol#L857

couple of "]" in this function that seems to not close a [

**Comment by Morteza3123** [comment]
The brackets are ok, but for better view we can declare the user first.

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/cb6c67b801a4c8f2187d44484a724bdda15d17ed/contracts/Exchange.sol#L900

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/cb6c67b801a4c8f2187d44484a724bdda15d17ed/contracts/Exchange.sol#L903

**Comment by Waltermelon-lang** [comment]
Sorry my mistake
