### ISSUE TITLE
funding fee relative to smallest side

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#28]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c7b8a4164694afa61cabd8f3e642e94c8fc30a5e/contracts/Exchange.sol#L855

Please set the funding fee relative to the smallest size of: 
x = min(allLongvBaycBalance, -1* allShortBaycBalance)
uint256 fundingFee = x * (indexPrice - oraclePrice)) / 24

So that the funding fee of long and short holders are net zero. 
Otherwise you can create collateral (real money) out nothing.

Example fundingFee =50$
Short position size 1000 (1 user), Long 10000 (2 users one, 2k one 8k)
Short pays 50 * 1k/1k, first long user 2k/10K * 50 and second long user 8k/10k * 50.

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/cb6c67b801a4c8f2187d44484a724bdda15d17ed/contracts/Exchange.sol#L872-L877

**Comment by Waltermelon-lang** [comment]
int256 minBaycBalance -> 
I would call this minOpenInterest

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/8347102a56aa17d097d5806c36100af0f0f5e430/contracts/Exchange.sol#L872
