### ISSUE TITLE
directly modify collateral

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#29]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c7b8a4164694afa61cabd8f3e642e94c8fc30a5e/contracts/Exchange.sol#L860

This solution seems to directly adjust users their collateral. 
My suggestion was to make a list of users virtual collateral in the main contract and 
sum: collateral = realcollateral + virtualcolleral, 
whenever a user wants to change their position. 
Is my suggestion viable at all?

Do you think your solution or this solution is can be optimized?

**Comment by Morteza3123** [comment]
Yes It can be better.

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/dc638d4e4d18889892e4c98f39ab2157401e90dd/contracts/Exchange.sol#L905

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/dc638d4e4d18889892e4c98f39ab2157401e90dd/contracts/Exchange.sol#L323-L326

**Comment by Waltermelon-lang** [comment]
So do you think saving it this way:
  mapping(address => int256) public virtualCollateral; //funding reward of each user
solves our issue?

**Comment by Morteza3123** [comment]
Yes It does.
