### ISSUE TITLE
totalInvestedValue and totalAssetSize

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#3]
Can you track the totalInvestedValue and totalAssetSize after each moment of change (trade/liquidation etc.)? -> usually where you currently track PNL.

**Comment by Morteza3123** [comment]
openLongOrder(if the orders match and position is created)
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/a6a9d396f2d227c5cc7acd6a9e1cdd145baea849/contracts/Exchange.sol#L303

openShortOrder(if the orders matchand position is created)
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/a6a9d396f2d227c5cc7acd6a9e1cdd145baea849/contracts/Exchange.sol#L359

closeLongPosition
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/e88a1cabd055488e39b856cb57ddb5c43e7a8c4d/contracts/Exchange.sol#L395

closeShortPosition
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/e88a1cabd055488e39b856cb57ddb5c43e7a8c4d/contracts/Exchange.sol#L429

hardLiquidate(by close pistions total invested value changes)
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/e88a1cabd055488e39b856cb57ddb5c43e7a8c4d/contracts/Exchange.sol#L546


partialLiquidate(by close pistions total invested value changes)
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/e88a1cabd055488e39b856cb57ddb5c43e7a8c4d/contracts/Exchange.sol#L524

**Comment by Waltermelon-lang** [comment]
this was a difficult one, but I think you did great
