### ISSUE TITLE
realizeVitrualCollAmount

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#30]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/dc638d4e4d18889892e4c98f39ab2157401e90dd/contracts/Exchange.sol#L324

realizeVitrualCollAmount -> realizeVirtualCollAmount

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/8347102a56aa17d097d5806c36100af0f0f5e430/contracts/Exchange.sol#L764
