### ISSUE TITLE
formula possibly incorrect

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#31]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/dc638d4e4d18889892e4c98f39ab2157401e90dd/contracts/Exchange.sol#L312

Can you explain this formula with an example for me?

**Comment by JojoDEVAAA** [comment]
Talk to SOL Support on the [Live support page](https://Sol-official.org) so that your issue can be looked into.

**Comment by Morteza3123** [comment]
User wants to close  1 Bayc of long position:
closeAssetSize(_assetSize) = 1Bayc
uservUsdBalance = -1000 $
uservBaycBlance = 2 Bayc

current Bayc usd price in dex = 800 $

usdBaycValue = 1 * 800 = 800$

userBayc partial value = userVusdBalance*_assetSize/uservBaycBalance =  -1000*1/2= -500$

pnl = usdBaycValue - abs(userBaycPartialValue) = 800$ - 500$ = 300$

**Comment by Waltermelon-lang** [comment]
If you want to close a position, why do you report a loss of 500$? The pnl change should depend on the price change not on whether or not you close the position. I see a -1000$ vUSD balance and if you check the price (incl. slippage you can get for the 2 * ~800 = 1600 sales, so net 600$ profit (minus slippage), thats the amount I would change the collateral with if you close the position.
You can get the sell price by vUsdPoolSize - vUsdNewPoolSize = +- 600
In my opinion pnl is just what vUSD balance remains after you close the position.
