### ISSUE TITLE
Why do we have two address inputs in the collateral read function?

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#34]
![image](https://user-images.githubusercontent.com/57764578/196548797-be9663f6-4622-473d-8003-d534a13041a8.png)

**Comment by Waltermelon-lang** [comment]
d

**Comment by Morteza3123** [comment]
For collateral, fist input is stabecoin address (in our testnet usdt is our stable coin) and second input is user address to check the collateral of him. 

it's a tuple mapping => collateral[usdc][user]
