### ISSUE TITLE
Descriptive error messsages

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#35]
Is there a way to be more descriptive in the error messages from the code?

**Comment by Morteza3123** [comment]
Etherscan shows the require error of the code for the reason we should check the require of the code. also we can check input  data to insure that they are correct

**Comment by Waltermelon-lang** [comment]
I assume you mean this is something we should do from the frontend, or do you mean to add anything in the smart contract?

**Comment by Morteza3123** [comment]
When one of function's requirement has not passed (for example user didn't approve token before deposit or price change will be more than 10% far from oracle) this makes metamask to shows error. In the frontend we should consider all this checkpoint before transaction and show it to user to know what is the problem. But in etherscan we dont have this ability to show error before transaction but in the frontend we can.

**Comment by Waltermelon-lang** [comment]
Ah oke, thanks for the explanation
