### ISSUE TITLE
Open position does not depend on margin

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#36]
When I open a position, I can immediately be at risk of being liquidated because I can open a position larger than the allowed margin.
For now during the testing, you can actually try to liquidate me and see how that works.
0x53FebBeE060F68CCE33Bd7785f352Ca3c7A205BB
But after I would like that to change.

**Comment by Waltermelon-lang** [comment]
function openLongPosition(uint256 _usdAmount) public {
  function openShortPosition(uint256 _usdAmount) public {

**Comment by Waltermelon-lang** [comment]
![image](https://user-images.githubusercontent.com/57764578/200135069-651bb07e-5755-4d02-ba37-4d0d57dc7642.png)

Furthermore, a new function 'Liquidateable' might be better; the position has to stay above the saveLevelMargin, not the AutoCloseMargin because then it can immediately be partially liquidated. 
This or you can change the exististing function to add the top range margin 
   if (userMargin > 0 && userMargin <= 40) { 
  ->    
  if (userMargin > 0 && userMargin <=  varX ) { 
  
Not sure which is better
FYI, you cant modify the _hardLiquidateable for that, since it is already in use by other functions.

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c7c3953aff43acec7b58e4244a21d87208272121/contracts/Exchange.sol#L644-L659

**Comment by Waltermelon-lang** [comment]
👍
