### ISSUE TITLE
renounceOwnership Ownable.sol

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#37]
function renounceOwnership() public virtual onlyOwner {
        _transferOwnership(address(0));
    }

Is it possible to renounce the ownership and still perform vital operations such as provide oracle price, liquidate and receive protocol fees?

**Comment by Morteza3123** [comment]
It's a function ownable standard (openzeppelin library). We dont have to use it but it's a function of ownable activities set by openzeppelin. 

https://docs.openzeppelin.com/contracts/2.x/api/ownership#Ownable-renounceOwnership--

**Comment by Waltermelon-lang** [comment]
I dont we will ever renounce ownership since we need it to be able to withdraw insurance and fees as owner from the smart contract I assume? 
Might as wel remove it if it saves any gas costs.

**Comment by Morteza3123** [comment]
It's part of the owner standard library and we can't remove it. Also it doesn't have gas cost for transaction because it's a function not a variable. So just pay gas for it on deploying the contract. And if we don't call it we don't pay gas for it.

**Comment by Waltermelon-lang** [comment]
Oke, thanks for informing me on these details. ;)
