### ISSUE TITLE
Public liquidation option can be removed in the future

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#38]
function partialLiquidate and partialLiquidateUsers have both an internal and a public. 
When we check in each step of every trade for liquidations public does not need to be able to liquidate users anymore afaik so it can be removed, or did you want to check how the contract was working?

**Comment by Morteza3123** [comment]
I thought that maybe in future versions we want to liquidate users using a bot for that reason I put this functions. But for now I can remove them so the code will be cleaner and need less gas to deploy.

**Comment by Waltermelon-lang** [comment]
yes please, please make sure you save your valuable work locally (as will I) and then we can make this smart contract as lean as possible. 
Being able to liquidate users was a requirement in the orderbook exchange, however right now it is no long a requirement. 
Furthermore, we can still built in an orderbook in later versions on top of the vAMM -> 
- two options: 
- Users can post a limit buy/sell order offchain with us and we submit the order the moment a certain price is triggered 
(this would be the low gas costs solution, but security risk for offchain getting hacked.
- Second option: add the orderbook as you already built it on top of the vAMM , this would increase the complexity 
onchain and the gas costs. 
Im interested in your opinion. 
Lets evaluate after the mvp, it does not have priority over the mvp and building out our product line.

**Comment by Morteza3123** [comment]
Ok, I remove it for now because we don't need it.
