### ISSUE TITLE
Solidity compiler bugs

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#39]
https://goerli.etherscan.io/address/0xd43B5F0cBdE76D1953FA05AE82080bb53993dd89#code
The contract mentiones compiler bugs, is this an issue?

![image](https://user-images.githubusercontent.com/57764578/199076564-e5b285f8-b190-40fa-bb27-9841f97ea82d.png)

Compiler specific version warnings:

The compiled contract might be susceptible to [StorageWriteRemovalBeforeConditionalTermination (medium/high-severity)](https://goerli.etherscan.io/solcbuginfo?a=StorageWriteRemovalBeforeConditionalTermination), [AbiReencodingHeadOverflowWithStaticArrayCleanup (medium-severity)](https://goerli.etherscan.io/solcbuginfo?a=AbiReencodingHeadOverflowWithStaticArrayCleanup), [DirtyBytesArrayToStorage (low-severity)](https://goerli.etherscan.io/solcbuginfo?a=DirtyBytesArrayToStorage), [InlineAssemblyMemorySideEffects (medium-severity)](https://goerli.etherscan.io/solcbuginfo?a=InlineAssemblyMemorySideEffects), [DataLocationChangeInInternalOverride (very low-severity)](https://goerli.etherscan.io/solcbuginfo?a=DataLocationChangeInInternalOverride), [NestedCalldataArrayAbiReencodingSizeValidation (very low-severity)](https://goerli.etherscan.io/solcbuginfo?a=NestedCalldataArrayAbiReencodingSizeValidation) Solidity Compiler Bugs.

**Comment by Morteza3123** [comment]
I will check the compiler and code for that related warnings.

**Comment by Waltermelon-lang** [comment]
Any update on this, is this even important at all? If not we can just close this issue as irrelavant

**Comment by Morteza3123** [comment]
Sorry, I looked for reason but I don't  know why this warnings happened. Please let me search again for the reason, I think it's happened through verifying contract.

**Comment by Morteza3123** [comment]
Solved. 

https://goerli.etherscan.io/address/0x9a99285696a1d5ee9bdfBE2ba0cBEB0281814374#code

**Comment by Waltermelon-lang** [comment]
Niceeeee
