### ISSUE TITLE
 totalPositionsvalue tracking

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#4]
//Total of user long and short positions
  function totalPositionNotional(address _user) public view returns (uint256) {
    uint256 latestPrice = nftOracle.showPrice(latestRequestId);
    uint256 totalPositionsvalue = 0;
    for (uint256 i = 0; i < positions.length; i++) {
      if (positions[i].longAddress == _user) {
        totalPositionsvalue += positions[i].positionSize * latestPrice;
      }
      if (positions[i].shortAddress == _user) {
        totalPositionsvalue += positions[i].positionSize * latestPrice;
      }
    }
    return totalPositionsvalue;
  }

Why is there an if condition if the formula: 
totalPositionsvalue += positions[i].positionSize * latestPrice;
is the same

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/a6a9d396f2d227c5cc7acd6a9e1cdd145baea849/contracts/Exchange.sol#L138

Each position has two side, user might be in the long side or in the short side if each position so I check both side to add them to the total position notional.

**Comment by Waltermelon-lang** [comment]
Oke perhaps slightly cleaner:
if (positions[i].longAddress == _user || positions[i].shortAddress == _user ) {
totalPositionsvalue += positions[i].positionSize * latestPrice;
}

**Comment by Morteza3123** [comment]
Yes, that would be better.

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/50719635f8f66113dc631162cb345c3ccd473abc/contracts/Exchange.sol#L138-L147

**Comment by Waltermelon-lang** [comment]
Perfetto, xxx
