### ISSUE TITLE
Liquidate yourself creates two transactions: the (partial) liquidation and the original transaction

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#40]
Right now it is possible to liquidate yourself, the liquidation then takes priority and the original transaction still follows after.
This causes a double transactions and the balance to go in the opposite way.

Perhaps you can add the exclusion that a user cannot liquidate themselves, instead they will just be able to do their transaction as if normal.

**Comment by Morteza3123** [comment]
True, I add this point.
