### ISSUE TITLE
Margin in the code

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#43]
![image](https://user-images.githubusercontent.com/57764578/200134824-48467981-2e12-4f6a-8576-96fc98e110ee.png)

Can you put (some of the remaining) margin variables in the code interactively?
Thx.

**Comment by Morteza3123** [comment]
It's done in the code.

**Comment by Waltermelon-lang** [comment]
if (userMargin > 0 && userMargin <= 40) {
-> if (userMargin > 0 && userMargin <= AutoCloseMargin) { 
I still see a few instance of 40,50,60.
Or did you mean you were planning to do this in the next update?

**Comment by Waltermelon-lang** [comment]
You put an int8 in front of saveLevelMargin, perhaps you can do that everywhere it is relevant.

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/49154352d089cfc03c96e7399355d7f9d0b57ea3/contracts/Exchange.sol#L645

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/79297eea1a0bca6a66492cddc97945327c220a81/contracts/Exchange.sol#L612

**Comment by Morteza3123** [comment]
They are all replaced in the right place

**Comment by Waltermelon-lang** [comment]
Some variable are typechecked and some are not.
F.e., why are you not typechecking discountRate but are typechecking AutoCloseMargin?
If this is important then why not for every variable everywhere?

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c271dc021cb575f80e83497688f92333cb0c6e9f/contracts/Exchange.sol#L28-L49

**Comment by Morteza3123** [comment]
Sometimes I need to multiply them by an int type variable, for that reason I convert them to int. But sometimes they are used with uint variables and I let them remain in the uint.
