### ISSUE TITLE
liquidation not checking every user

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#44]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/6c362f228cc4e9e6ecd1f4465ae7c1f0f4072187/contracts/Exchange.sol#L279

Here we are testing whether the user itself is partially or completely liquidatable. Right now this function is excess since, with the newly added function to stay above 60%, the user will never be liquidatable, so we do not need to check for that, we just need to run the partially and fully liquidate functions for all the other users without a condition IMO. 

A users margin can go below zero, if people before them get liquidated in the same transaction, these people currently do not get liquidated. I would like these people also to get liquidated and I would like the virtualCollateral balance of users who profit from this liquidation to be lowered with the negative value, with the lowering amount/value relative to the weight of their position size. 
This ensures there is never any bad debt

**Comment by Morteza3123** [comment]
For your first paragraph, by doing that user can liquidate himself/hersalf. Are you ok with that ?

For your second point, I will change the liqudate checker to catch negative margin also. But changing virtualCollateral of other users need loop and it's extra work and need extra gas.

**Comment by Waltermelon-lang** [comment]
"For your first paragraph, by doing that user can liquidate himself/hersalf. Are you ok with that ?"
I would like a user not to be able to liquidate themselves, regardless of hard of partial liquidate. 
If a user would try to improve the balance of the position, by partially closing for example, they would get a double transaction from both liquidating themselves and thereafter from again try to extra close an already closed position, which might cause their position to shoot in the other direction (long to short or short to long). 

Second point: its necessary/vital to charge users for this in order to retain neutrality, otherwise users can close their trades with net negative asset balance and other users would be able to withdraw (profit from these liquidations) to much, thus create real money out of nothing.

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/ed0168345d58f91311e545ac626d2d971983e784/contracts/Exchange.sol#L947-L966


https://github.com/nexlabs22/Nex-Dex-Contracts/blob/ed0168345d58f91311e545ac626d2d971983e784/contracts/Exchange.sol#L758-L826
