### ISSUE TITLE
Hard liquidation before partial liquidation or while loop

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#45]
We should probably try to liquidate people that are hard liquidable first over people that are only partially liquidable. 
I see 4 instances: open long/short and close long/short. 

Knowing that a liquidation can trigger another due to the price change.
Is it true that we cannot loop (in a _while >0 liquidatable_, go through that list) over the liquidations within are single transaction as that would possibly blow up a transactions gas cost. 
If we could, than we can check for all partial liquidations first, continue looping until we had all of them, and then check for all hard liquidations and continue looping until we have all of them.

**Comment by Morteza3123** [comment]
Yes we can liquidate aser first after that we can partial liquidate users.

openLongPosition(){
   hardLiquidate();
   partialLiquidate();
}

 If it's ok I would change the code.

**Comment by Waltermelon-lang** [comment]
Yes please

**Comment by Waltermelon-lang** [comment]
This issue is still open for the closing positions

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/79297eea1a0bca6a66492cddc97945327c220a81/contracts/Exchange.sol#L282-L284

**Comment by Waltermelon-lang** [comment]
👍
