### ISSUE TITLE
rename all Insurance instances ContractFee

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#47]
Ill leave this thought open in case you agree/disagree with the idea to not have an insurance fund.
Then we would be better of renaming this, since it leads to confusion with anybody who reads the contract.

Also instead of removeInsuranceFunds I would like collectContractFee (so Collect instead of "remove")

**Comment by Morteza3123** [comment]
So you want to change the usecase of insurance funds to contract fee? or it's just a renaming ?

**Comment by Waltermelon-lang** [comment]
The usecase has already changed. Right now you can deposit into the insurance fund, but it does nothing. Basically in the current setup, the insurance fund is just for withdrawing.

**Comment by Morteza3123** [comment]
Ok we can remove deposit insurance function. agree?

**Comment by Waltermelon-lang** [comment]
agree, might be confusing to anybody trying to understand our code

**Comment by Morteza3123** [comment]
Done
