### ISSUE TITLE
initial virtual pool called only once?

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#48]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/69c41fa539dd75b81d5e8f3d7a9bdc4b735bb49e/contracts/Exchange.sol#L140

Is it only possible to call the initialVirtualPool function once, at creation? 

If the owner is compromised, they can change the amounts in the pool, open a position in a certain direction and essentially drain the pool by giving themselves a favourable price after they already opened a position.

**Comment by Morteza3123** [comment]
If you want I can make it initializable, means that can called only once.

**Comment by Waltermelon-lang** [comment]
*can

yes please.

**Comment by Waltermelon-lang** [comment]
I see you fixed it, thxs, really making progress here
