### ISSUE TITLE
Potentially save gas costs with smaller variables?

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#49]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/69c41fa539dd75b81d5e8f3d7a9bdc4b735bb49e/contracts/Exchange.sol#L48

![image](https://user-images.githubusercontent.com/57764578/201584499-c8faea1e-b13d-49ae-a778-90e3918d43ed.png)

We might be able to save gas costs by storing these in uint128 or even smaller and grouping them together.
Then if the oracle variable/collateral comes in as a 10^18 or for example the stablecoin then we need to divide those to get the correct amount, but this division might be cheaper than the memory access.

https://techblog.geekyants.com/tips-and-tricks-in-solidity

**Comment by Morteza3123** [comment]
Yes, It should be considered.

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/d8addd5bdef19d05562106d16107b07bdd4794fc/contracts/Exchange.sol#L48-L52

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/d8addd5bdef19d05562106d16107b07bdd4794fc/contracts/Exchange.sol#L58


https://github.com/nexlabs22/Nex-Dex-Contracts/blob/d8addd5bdef19d05562106d16107b07bdd4794fc/contracts/Exchange.sol#L41-L46

**Comment by Waltermelon-lang** [comment]
well done. No more need to reduce variable size. To repeat your arguments:
Deep stack error, and adding many variables in each function to achieve calculation big numbers and storing small numbers is required.
