### ISSUE TITLE
calculatePartialLiquidateValue

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#5]
//calculate liquidation amount to turn back the user margin to the save level(60%)
  function calculatePartialLiquidateValue(address _user) public view returns (uint256 x) {
    uint256 totalAccountValue = totalAccountValue(_user);
    uint256 totalPositionNotional = totalPositionNotional(_user);
    uint256 numerator = (totalPositionNotional * saveLevelMargin) / 100 - totalAccountValue;
    uint256 denominator = saveLevelMargin / 100 - discountRate / 100;
    x = numerator / denominator;
  }

Numerator and denominator are incorrect as far as I can see from the updated excalidraw.

![liqValue](https://user-images.githubusercontent.com/57764578/191734512-2038cf91-9fcf-41c7-80b8-d2c665d82f07.PNG)

**Comment by Morteza3123** [comment]
They are the same, I just change the place of them to avoid negative numbers. Because (A < SLM*N) and (discount/100 < SLM);

x = (SLM*N - A)/(SLM - Discount/100);

**Comment by Waltermelon-lang** [comment]
I agree with this formula, x = (SLM*N - A)/(SLM - Discount/100);
but it dont think it matches the code (the "/100" are do not match)
uint256 denominator = saveLevelMargin / 100 - discountRate / 100; 
->
uint256 denominator = saveLevelMargin - discountRate / 100;

uint256 numerator = (totalPositionNotional * saveLevelMargin) / 100 - totalAccountValue;
->
uint256 numerator = totalPositionNotional * saveLevelMargin - totalAccountValue;

**Comment by Morteza3123** [comment]
Save level margin is 60 (stored in uint) so for making it in percent I divided it by 100.

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/fffd82d9b5f496d914c70203ac289c6f9888ace5/contracts/Exchange.sol#L38

**Comment by Waltermelon-lang** [comment]
AH, oke thanks!
