### ISSUE TITLE
Or statement not possible?

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#50]
line 617   if (accountValue > 0 && positionNotional > 0) {

Count you merge the two into?:
 if ((accountValue > 0 || accountValue <0) && positionNotional > 0) {

Even better maybe, something that you do later: != 0

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/79297eea1a0bca6a66492cddc97945327c220a81/contracts/Exchange.sol#L583

**Comment by Waltermelon-lang** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c271dc021cb575f80e83497688f92333cb0c6e9f/contracts/Exchange.sol#L599-L608

second if condition is same as first, can be merged as !=0.

I found this by ctrl+f search accountValue > 0 . 
I recommend whenever I have an issue that you check for all instances where a given suggestion might apply to.

**Comment by Morteza3123** [comment]
Yes thanks. 

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/980ada80f26a6858bec6a5ecaa12ce1348df6d42/contracts/Exchange.sol#L601-L607
