### ISSUE TITLE
unsigned integer questions

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#51]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/ed0168345d58f91311e545ac626d2d971983e784/contracts/Exchange.sol#L651

![image](https://user-images.githubusercontent.com/57764578/201834252-e5159714-a5c2-48b2-a0e2-c5e9ec78b2d8.png)

I see you changed a bunch of code from uint to int to account for the fact that variables can have negative values. 
However, in line 650 and 651:
uint newMargin = 100*uint(accountValue)/newPositionNotional;
if (newMargin > 0 && newMargin <= saveLevelMargin) {

You check whether newMargin is >0 when its a unsigned, so it can never be negative there right? If I understand correctly than newMargin should be an int not uint. 

652  if (newMargin > 0 && newMargin <= saveLevelMargin) {
newMargin !=0

**Comment by Waltermelon-lang** [comment]
I see the similar issue in line 843 and 849

  **int256 totalAccountValue** = _getNewAccountValue(_user, _vBaycNewPoolSize, _vUsdNewPoolSize);

 uint256 numerator = totalPositionNotional*saveLevelMargin/100 > **uint(totalAccountValue)** ? totalPositionNotional*saveLevelMargin/100 - uint(totalAccountValue) : uint(totalAccountValue) - totalPositionNotional*saveLevelMargin/100;

Is it your intention to go convert from int to uint?

**Comment by Waltermelon-lang** [comment]
Contracts/blob/ed0168345d58f91311e545ac626d2d971983e784/contracts/Exchange.sol#L820

If you go from 
  **int256 negativeValue** = _getNewAccountValue(_user, _vBaycNewPoolSize, _vUsdNewPoolSize);
uint(negativeValue)

It is like taking the positive() function
Contracts/blob/ed0168345d58f91311e545ac626d2d971983e784/contracts/Exchange.sol#L246

So either we need that function to convert a signed number to an unsigned number, or we can just
cast it in a positive value using uint256("example of int256"). But in the latter we can remove all instances of Positive() function
and just use the type conversion casting.

**Comment by Morteza3123** [comment]
Sorry in two parts it should be edited.

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/49154352d089cfc03c96e7399355d7f9d0b57ea3/contracts/Exchange.sol#L635-L650

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/49154352d089cfc03c96e7399355d7f9d0b57ea3/contracts/Exchange.sol#L846-L862

**Comment by Morteza3123** [comment]
Basically uint(number) doesnt change the negative to positive and for doing that I wrote two function in smart contract:
positive(negative int) => positive uint;
absoluteInt(negative int) => positive uint;
uint(positive int) => positive uint;

I changed some poiont as you said, thanks.

**Comment by Waltermelon-lang** [comment]
Perhaps you can remove either 
function absoluteInt or  function positive, I dont see their difference:

  function absoluteInt(int256 _value) public view returns (int256) {
    if (_value < 0) {
      return -(_value);
    } else {
      return _value;
    }
  }

  function positive(int256 _amount) public view returns (uint256) {
    if (_amount < 0) {
      int256 posAmount = -(_amount);
      return uint256(posAmount);
    } else {
      return uint256(_amount);
    }
  }

**Comment by Morteza3123** [comment]
You know, in some points your right, absolute is for positive int, but some times I want to convert negative int to positive uint and by just using absolute, It's been like (uint(absolute(negativeInt))) and it seems not good in the code. Against it, I simply use positive(negativeInt) . But suggest having both of them to make code simpler. But if you want, I can rename positiveUint()

**Comment by Waltermelon-lang** [comment]
Oke I get it, it is more self explanatory. Then you can keep both.

collateral withdraw cannot be negative:
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/49154352d089cfc03c96e7399355d7f9d0b57ea3/contracts/Exchange.sol#L171

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/49154352d089cfc03c96e7399355d7f9d0b57ea3/contracts/Exchange.sol#L171-L182

I just check the margin ( that can be negative) and if margin is lower than save level margin user can not withdraw collateral.

**Comment by Waltermelon-lang** [comment]
Sorry I was flipping the meaning of uint and int in my head.
