### ISSUE TITLE
github copilot

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#52]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/ed0168345d58f91311e545ac626d2d971983e784/contracts/Exchange.sol#L154

You can replace below quotes, I have improved them because a user might be able to read them I assume. 
If you would like help with this, I can recommend Grammarly, it is smarter than for example google docs.

"You should wait at least 12 hours after latest update" -> "You should wait at least 12 hours after the latest update."
 "newFee should be between 1 to 500" -> "The newFee should be between 1 and 500 (0.01% - 5%)."
 
"You cannot withdraw because your margin rate is the lower than saveMargin level" -> "
"You cannot withdraw because your margin is lower than the saveMargin level."

"Desire amount is more than collateral balance" -> 
"Requested withdrawal amount is larger than the collateral balance."

"out of vitrual collateral balance" -> 
"Requested amount is larger than the virtual collateral balance."

 "You can't move the price more than 10% far from the oracle price" ->
 "You can't move the price more than 10% away from the oracle price." 

"You can't open this position because you probability will be liquidated by this margin" ->
"Insufficient margin to open position with requested size."

  "You dont have enough asset size to close the long position" ->
"Reduce only order can only close long size equal or less than the outstanding asset size." 
 
 "You dont have enough asset size to close the short position" ->
"Reduce only order can only close short size equal or less than the outstanding asset size." 

  "You dont have enough asset size to close the all positions" -> 
"Reduce only order can only close size equal or less than the outstanding asset size." 

2x line 766 same: 
 "user can not be liquidate" -> 
"User is not hard liquidatable."

"user can not be partially liquidated" ->
"User is not partially liquidatable."

 "greater than insurance funds balance" ->
 "Requested collect amount is larger than the ContractFee balance."

**Comment by Morteza3123** [comment]
Thanks for your help, I changed them. I should use some helpful tools to do that.

**Comment by Waltermelon-lang** [comment]
Github co-pilot might also helpful in this matter, let me keep this issue open as an reminder until you have it.

**Comment by Morteza3123** [comment]
Ok, thanks.
