### ISSUE TITLE
removeActiveUser without condition and no computation needed for resetting user balances to zero

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#54]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/ed0168345d58f91311e545ac626d2d971983e784/contracts/Exchange.sol#L776
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/ed0168345d58f91311e545ac626d2d971983e784/contracts/Exchange.sol#L777

This might save some computation: 

uservBaycBalance[_user] = 0
uservUsdBalance[_user] = 0

   if (uservBaycBalance[_user] == 0 && uservUsdBalance[_user] == 0) {
        _removeActiveUser(_user);
      }

-> 
You can run the remove active user function without condition. 
   _removeActiveUser(_user);

I assume that  _removeActiveUser(_user); does not reset their balances to zero, otherwise you could skip these as well:
uservBaycBalance[_user] = 0
uservUsdBalance[_user] = 0

**Comment by Waltermelon-lang** [comment]
I assume for line

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/ed0168345d58f91311e545ac626d2d971983e784/contracts/Exchange.sol#L713
Contracts/blob/ed0168345d58f91311e545ac626d2d971983e784/contracts/Exchange.sol#L714

in the _hardLiquidate(

Can you also just do?:

uservBaycBalance[_user] = 0
uservUsdBalance[_user] = 0

since we are just completely closing their positions

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/79297eea1a0bca6a66492cddc97945327c220a81/contracts/Exchange.sol#L709-L712


https://github.com/nexlabs22/Nex-Dex-Contracts/blob/79297eea1a0bca6a66492cddc97945327c220a81/contracts/Exchange.sol#L735-L739

**Comment by Waltermelon-lang** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c271dc021cb575f80e83497688f92333cb0c6e9f/contracts/Exchange.sol#L807

-= -> 0

**Comment by Morteza3123** [comment]
Sorry. 

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/4b655ffa9a439b64b93741b1ac9418ad8f5c17f8/contracts/Exchange.sol#L809
