### ISSUE TITLE
twice positive

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#56]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/ed0168345d58f91311e545ac626d2d971983e784/contracts/Exchange.sol#L1040

You do twice the positive function, so you also remove both. example -4/-4 =1 = 4/4

**Comment by Morteza3123** [comment]
Funding fee is uint and can not multiplied by negative number ( positive() function also convert int to uint).

**Comment by Morteza3123** [comment]
fadingfee(uint) * uservBaycBalance(int) => error

**Comment by Waltermelon-lang** [comment]
Another option would be to put the fundingFee last
 uint256 userFundingFee = uservBaycBalance[user]/allShortBaycBalance * fundingFee 
Whichever you prefer, its not really important since this function is only called by onlyOwner and it shouldnt have to much costs anyway.

**Comment by Morteza3123** [comment]
It's the same:

uservBaycBalance[user]/allShortBaycBalance * fundingFee = int/int * uint;

positive() convert them to uint also. Yes I suggest current structure.

**Comment by Waltermelon-lang** [comment]
oke, thanks for the knowhow, I understand now
