### ISSUE TITLE
function checks whether user is liquidatable but then proceeds to liquidate other users

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#57]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/ed0168345d58f91311e545ac626d2d971983e784/contracts/Exchange.sol#L365

If the user is trying to close a position, I do not want to check whether a user is liquidatable, they can close their position without getting liquidated.

Before we close a position we still run the liquidations on the other users. 

Its an issue for both these functions: 

  function _closeLongPosition(address _user, uint256 _assetSize) internal {
  function _closeShortPosition(address _user, uint256 _assetSize) internal {

Lets run these, in this order, without the condition: 

  _liquidateUsers(vBaycNewPoolSize, vUsdNewPoolSize);
  _partialLiquidateUsers(vBaycNewPoolSize, vUsdNewPoolSize);

Also: 
 function **_liquidateUsers**(uint256 _vBaycNewPoolSize, uint256 _vUsdNewPoolSize) internal {  -> 
function **_hardLiquidateUsers**(uint256 _vBaycNewPoolSize, uint256 _vUsdNewPoolSize) internal {

might be an a bit more clear distinction between partial and hard liquidate.

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/49154352d089cfc03c96e7399355d7f9d0b57ea3/contracts/Exchange.sol#L365-L367
