### ISSUE TITLE
function does not update to new pool sizes?

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#58]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/ed0168345d58f91311e545ac626d2d971983e784/contracts/Exchange.sol#L980

should this function not update the new pool sizes as a variable that is returned from this function?
Otherwise if you liquidate multiple users you liquidate all users according to the same pool price, 
this would move the pool price less than its should.

Same goes for all (hard)Liquidate instances

**Comment by Morteza3123** [comment]
Yes now they are updating after each user liquidation. 

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/49154352d089cfc03c96e7399355d7f9d0b57ea3/contracts/Exchange.sol#L283


https://github.com/nexlabs22/Nex-Dex-Contracts/blob/49154352d089cfc03c96e7399355d7f9d0b57ea3/contracts/Exchange.sol#L962-L983

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/49154352d089cfc03c96e7399355d7f9d0b57ea3/contracts/Exchange.sol#L747-L749

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/49154352d089cfc03c96e7399355d7f9d0b57ea3/contracts/Exchange.sol#L365-L367

**Comment by Waltermelon-lang** [comment]
Looks good to me!
