### ISSUE TITLE
Withdraw collateral

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#6]
//withdraw collateral
  function withdrawEther(uint256 _amount) public {
    uint256 userMargin = getUserMargin(msg.sender);
    uint256 totalPositionNotional = totalPositionNotional(msg.sender);
    require(
      totalPositionNotional == 0 || userMargin > 60,
      "You cannot withdraw because your margin rate is the lower than saveMargin level"
    );
    require(
      collateral[ETHER][msg.sender] >= _amount,
      "Desire amount is more than collateral balance"
    );
    collateral[ETHER][msg.sender] = collateral[ETHER][msg.sender].sub(_amount);
    payable(msg.sender).transfer(_amount);
    emit Withdraw(ETHER, msg.sender, _amount, collateral[ETHER][msg.sender]);
  }

I would like that the maximum withdrawable amount is until userMargin minimal is 60 if there is a positionNotional. (if they have no position than ofcourse they can go to zero)

**Comment by Morteza3123** [comment]
Ok, first I calculate the new margin if this amount withdraws, if new margin is smaller than save level margin(60) the function will not be executed.

uint256 ethPrice = ethPrice();
    uint usdAmount = _amount*ethPrice/1e18;

    uint256 userMargin = getUserMargin(msg.sender);
    uint256 totalPositionNotional = totalPositionNotional(msg.sender);
    uint256 totalAccountValue = totalAccountValue(_user);
    uint newAccountValue = totalAccountValue - usdAmount;
    uint newMargin = 100*newAccountValue/totalPositionNotional;
    require(
      newMargin > 60,
      "You cannot withdraw because your margin rate is the lower than saveMargin level"
    );

**Comment by Waltermelon-lang** [comment]
excellent
