### ISSUE TITLE
hard before partial

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#60]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/49154352d089cfc03c96e7399355d7f9d0b57ea3/contracts/Exchange.sol#L366-L367

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/49154352d089cfc03c96e7399355d7f9d0b57ea3/contracts/Exchange.sol#L423-L424

Can you do the hard liquidate first? Similar to other ones.

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/79297eea1a0bca6a66492cddc97945327c220a81/contracts/Exchange.sol#L423-L424
