### ISSUE TITLE
positive(totalAccountValue) works mathematically but makes no sense

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#61]
You take the positive of totalAccountValue, but if the totalAccountValue is negative, you cannot just flip this to positive from a logic perspective.
 
Simplest solution is do a condition:

if expectedAccountValueAfterPartialLiquidation < 0:
skip this user. 
This user will come back in the next transaction as either a hard or a hardNegativeLiquidate

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/49154352d089cfc03c96e7399355d7f9d0b57ea3/contracts/Exchange.sol#L841

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/49154352d089cfc03c96e7399355d7f9d0b57ea3/contracts/Exchange.sol#L858

If a users account value is for example close to zero and you partially liquidate them, then they can go below zero, which is not accounted for in the partial liquidate function (but is in the negativeHardLiquidation.

**Comment by Morteza3123** [comment]
I check them in _ispartialLiquidatabale() function if the new margin is not between 40 and 50, the loop skip user.

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/79297eea1a0bca6a66492cddc97945327c220a81/contracts/Exchange.sol#L664-L676

**Comment by Waltermelon-lang** [comment]
It seems to me under the current circumstances of a user being between 40 and 60% margin that 
uint256 numerator = totalPositionNotional*saveLevelMargin/100 > positive(totalAccountValue) ?
This condition is always true,
Furthermore if it would be false, the second part of the equation is just to ensure that it gives a non-negative value for the unsigned numerator variable. 
Perhaps you can remove this condition, or just wrap the whole equation in a positive() if it that removes warnings for you.

**Comment by Morteza3123** [comment]
True.

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/4b655ffa9a439b64b93741b1ac9418ad8f5c17f8/contracts/Exchange.sol#L836-L838
