### ISSUE TITLE
setFundingRate() is not a liquidation cover

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#62]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c271dc021cb575f80e83497688f92333cb0c6e9f/contracts/Exchange.sol#L1025

Al instances of liquidationCover in the setFundingRate should be recalled userFundingFee.
liquidation cover only occurs when a user has negative balance (inside the _hardNegativeLiquidate function).

**Comment by Morteza3123** [comment]
Oh, my fault.

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/4b655ffa9a439b64b93741b1ac9418ad8f5c17f8/contracts/Exchange.sol#L1048-L1055
