### ISSUE TITLE
-pnl -> pnl

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#65]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/e0b3f246301585967665e5f3dfc4443f38f02f94/test/unit/Exchange/Exchange.spec.ts#L227

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/e0b3f246301585967665e5f3dfc4443f38f02f94/test/unit/Exchange/Exchange.spec.ts#L344

PNL : if there is profit realized it should be added and viceversa

**Comment by crazy-dev-git** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/e0b3f246301585967665e5f3dfc4443f38f02f94/contracts/Exchange.sol#L473
I simulated the workflow of a smart contract

**Comment by Waltermelon-lang** [comment]
What I am trying to say is if PNL is positive say 10 we 
'realize' via:
collateral +10 and (PNL = 0 or PNL -= 10)
not -pnl, that would be collateral -10. 
The sign is wrong afaik.
