### ISSUE TITLE
staying closer to the source code not to introduce an extra variable

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#68]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/e0b3f246301585967665e5f3dfc4443f38f02f94/utils/exchange.ts#L155-L170

I see you write short notation for many of the solidity lines because you are no longer constraint f.e. by gas reduction issues to use things such as unsigned integers. 

However, I would like you to stay closer to the source code even if you can reduce the amount of code lines. 
This makes it easier for me to check if the testing code matches the source code and therefore I know when the 
testing code fails that the source code fails and not because the testing code was actually not matching. ->
ergo we are introducing an extra variable

I like the fact that you breakdown certain functions into their steps, to take a better look at the processes, but also I would like to run functions as a whole, like function openLongPosition(uint256 _usdAmount) public { 
without predicting which steps will happen. This would allow me to check for any 'unpredictable results' aka functions that would run but you didn't predict before that they would. You could considering running the console.table() in various parts of open/close-Long/Short-Position functions to account for the liquidation steps.

In general, I would just copy paste the source ode logic where possible and convert any solidity logic into typescript logic. 
This will also make it easier in the future to update this file based on changes in the .sol file.

**Comment by crazy-dev-git** [comment]
Yeah, you are right. Of course, the purpose of this mock pool is just test smart contracts. So I was going to establish the test pool as same as smart contract's. Something like reduced map of smart contract. 

And 'open/close-Long/Short-Position' functions on test are mock functions. Right now, testing is focus these feature. So I broke down these and took a look at test scripts. Of course, if we test 'hardliquidate' function, then I will breakdown this and separate step by step. 
As soon as possible, I will make 'open positions' function as a whole like smart contract. 
And I agree with your opinion to copy & paste the source code of logic to test even though test scripts will be bigger.

**Comment by Waltermelon-lang** [comment]
Oke good stuff, looking forward to your update.

**Comment by crazy-dev-git** [comment]
@Waltermelon-lang Please check the code.
I think this issue is already resolved.

**Comment by Waltermelon-lang** [comment]
agree
