### ISSUE TITLE
indexPrice

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#7]
uint256 indexPrice = 0;
    if (lowestShortPrice < highestLongOrderPrice) {
      indexPrice = (highestLongOrderPrice - lowestShortPrice) / 2 + lowestShortPrice;
    }
    if (lowestShortPrice > highestLongOrderPrice) {
      indexPrice = (lowestShortPrice - highestLongOrderPrice) / 2 + highestLongOrderPrice;
    }
    return indexPrice;
  }

-> simpler formula no if condition required:
 (highestLongOrderPrice + lowestShortOrderPrice) / 2
example (6+8)/2 = 7 or (8+6)/2 = 7 regardless.

**Comment by Morteza3123** [comment]
True, I changed them thanks.

indexPrice = (highestLongOrderPrice + lowestShortOrderPrice) / 2;

**Comment by Waltermelon-lang** [comment]
👍
