### ISSUE TITLE
What happens if user request zero withdrawal?

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#76]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/f6163cec557826eed0b79c4eec3b1a7b2961b501/contracts/Exchange.sol#L232-L242

If a users requests zero, the transaction will not fail, on the requirement, but it will not show an error message.
Maybe we should run this function only when the requested amount is larger than zero and show an error message
inside the function when a user requests zero. 

Furthermore I dont understand this formula:
    int256 realizeVirtualCollAmount = (virtualBalances[_user].virtualCollateral * int256(_assetSize)) /
      virtualBalances[_user].uservBaycBalance;

That is used as input to realize virtualColl, to me if you want to realize $700 in usdc, then the amount is #700. 
For that perhaps its better to calculate the fundingFee in usdc -> so the open interest * exchange rate 
to the get open interest in usdc.

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/2cee3c658d7c3cb979135f30fbd89d64eaac4d57/contracts/Exchange.sol#L232-L242

I added checkpoint about that. 
Also about your question as you know user may want to close part of the position. So by this line we calculate realize virtual collateral related to  part of the position not all of (of course if we want to close all positoin all vCollateral will be realized). 
For example if user wants to close half of the positoin we realize half of virtual collateral.

**Comment by Waltermelon-lang** [comment]
Thank you for your update and feedback.
I consider the virtualCollateral balance only a temporary one to save gas costs, agree?
Therefore, upon any transaction this balance can be closed completely and put in the collateral balance, following
 virtualBalances[_user].virtualCollateral -= _amount;  ->  virtualBalances[_user].virtualCollateral = 0 and line 240 can also be put to zero. 
 The combined balance of the virtualCollateral + collateral is always used for calculations, so there is no benefit to the user in holding any virtualCollateral balance, regardless of whether its positive or negative.
 
 Another one of my issue, an this refers to the last part when I opened this issue is that **_amount** is the amount you change the collateral and virtual collateral with, so that can only be usdc (not BAYC). However, fundingFee calculates in the other coin (BAYC) and influences the virtualCollateral. Thus the fundingFee should be calculated in usdc and currently it is in BAYC. 
_Fundingfee_ is calculated by _openInterest_ which is calculated by _getAllLongvBaycBalance_ , so it is calculated in BAYC and not USDC. One option would be to multiply the fundingFee by the currentPrice ( in usdc/bayc) to get the fundingfee in usdc. I think this is better than directly calculating the open interest in usdc since that would not keep into account change in price of the BAYC part of the user position.

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/9af89bd3942e8f770e7f05b5018d30f825c2935e/contracts/Exchange.sol#L973-L976

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c369b24e5dcf7f69a868690a03d3c2022d74b0f3/contracts/Exchange.sol#L230-L242

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c369b24e5dcf7f69a868690a03d3c2022d74b0f3/contracts/Exchange.sol#L435-L438

I removed require from realizevCollateral function and now in other functions we don't call realize amount when user doesn't have any vCollateral to be realized
