### ISSUE TITLE
Why are you leaving 0.1?

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#78]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/9af89bd3942e8f770e7f05b5018d30f825c2935e/test/unit/Exchange/Exchange.spec.ts#L244

**Comment by crazy-dev-git** [comment]
It is from JavaScript Number precision issue. I am going to overcome this problem from now on.

**Comment by crazy-dev-git** [comment]
https://github.com/MikeMcl/big.js/issues/45#issuecomment-104211175

We have three options to overcome this issue.
 - big.js
 - bignumber.js
 - decimal.js

I am going to use bignumber.js in test. @Waltermelon-lang @Morteza3123 Please let me know if you have any other opinion.

**Comment by Waltermelon-lang** [comment]
Oke great, yeah good to contact Morteza he might now best.

**Comment by crazy-dev-git** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/feat/update-test-pool/test/unit/Exchange/Exchange.spec.ts#L297-L302
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/feat/update-test-pool/utils/basics.ts#L10

I have resolved the accuracy problem of test pool. All values are exactly the same as the smart contract. Diff is 0

**Comment by Waltermelon-lang** [comment]
perfect thanks
