### ISSUE TITLE
add uniswap minimum amount out.

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#79]
Revert a transaction with the correct error message if the price moves more than a user is willing to tolerate. 
Similar to Uniswap.

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/aaf3665b022d7afdd5354ab82d7a1748c6002797/contracts/Exchange.sol#L919-L989

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/aaf3665b022d7afdd5354ab82d7a1748c6002797/contracts/Exchange.sol#L991-L1063

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/aaf3665b022d7afdd5354ab82d7a1748c6002797/contracts/Exchange.sol#L330-L334

I worked alot on this feature, by having this two call functions (getMinimumLongBaycOut, getMinimumShortBaycOut) user can find out exact bayc amount that he/she receives in open long or short positions after hard and partial liquidation of other users ( he/she see this  minimum bayc amount before starting transaction by calling each of this two call functions for free without gas used). 

Also user can put minimum bayc amount that he/she want to have in the input of the open position functions

**Comment by Waltermelon-lang** [comment]
Good work, math seems to check out! I see a lot of coding also with changing many uint to uint256 
Could you also the minAmtOut to closeLongPosition, closeShortPosition and closePositionComplete?

Finally a thought: I would consider making this minAmtOut (limit order) function optional, that is if the user does not provide a value, it is not checked for, then from the front end, we will automatically enable it at 5% or 10% from the current price, but the user can turn it off if they so desire (with a warning message ofcourse that it is saver to place a limit order, but sometimes users just want to rush a trade in my experience). I am reading optional variables in Solidity do not exist, so when we "turn off" limit from the frontend we can provide it for example with 0x0 as a variable value and check for it by 
if (minAmtOut !== 0x0){ require...}
What are your thoughts?

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c369b24e5dcf7f69a868690a03d3c2022d74b0f3/contracts/Exchange.sol#L1068-L1140


https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c369b24e5dcf7f69a868690a03d3c2022d74b0f3/contracts/Exchange.sol#L1144-L1213

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c369b24e5dcf7f69a868690a03d3c2022d74b0f3/contracts/Exchange.sol#L402-L421

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/c369b24e5dcf7f69a868690a03d3c2022d74b0f3/contracts/Exchange.sol#L461-L479
