### ISSUE TITLE
highestLongerOrderPirce, lowestShortPrice

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#8]
uint256 highestLongOrderPrice = longOrders[longOrders.length - 1].price;
 uint256 lowestShortPrice = shortOrders[shortOrders.length - 1].price;

please rename either one of them, f.e. lowestShortPrice = lowestShortOrderPrice
for consistency in nomenclature

**Comment by Morteza3123** [comment]
Solved.

uint256 highestLongOrderPrice = longOrders[longOrders.length - 1].price;
 uint256 lowestShortOrderPrice = shortOrders[shortOrders.length - 1].price;

**Comment by Waltermelon-lang** [comment]
;)
