### ISSUE TITLE
Could you type these functions out for me

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#80]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/9e180fb85e6220dfc6ba79e0dd0357b5b312f8dd/utils/exchange.ts#L230-L234

I can imagine the above code is correct, however, for me to check the correctness and and future upgrades any sort of mathematical short writing makes it harder for me to follow the steps from the original code. 

Can you just copy the variables in the below function, paste them in yours and adjust them to function in your code.
This for all the relevant functions. If you could do that after step one of the steps you shared with me and rerun the test and share with me to see if there's any change. This for all the pool. functions and/or where its possible/relevant. I would like the make minimal code adjustments, only the ones required to go from .sol to to .ts files for the functions so we know the are a 1:1 copy and we know we are testing the .sol file and not the test file itself.

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/aaf3665b022d7afdd5354ab82d7a1748c6002797/contracts/Exchange.sol#L245-L253

**Comment by Kunkka0822** [comment]
[https://github.com/nexlabs22/Nex-Dex-Contracts/blob/main/contracts/Exchange.sol#L246-L252](url)

**Comment by Kunkka0822** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/main/contracts/Exchange.sol#L246-L252

**Comment by Kunkka0822** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/main/contracts/Exchange.sol#L246-L252

**Comment by Kunkka0822** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/9e180fb85e6220dfc6ba79e0dd0357b5b312f8dd/utils/exchange.ts#L230-L234

**Comment by crazy-dev-git** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/7912e8be18b650363fe878db0f21420e9d23dad9/utils/contracts/exchange/contract.ts#L284-L292

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/aaf3665b022d7afdd5354ab82d7a1748c6002797/contracts/Exchange.sol#L245-L253

This is current status

**Comment by crazy-dev-git** [comment]
@Waltermelon-lang  While developing test system, I did do everything to make 1:1 copy possible from .sol file to .ts file
But unfortunately, javascript doesn't support operator overloading.

**Comment by Waltermelon-lang** [comment]
It look goods to me!
