### ISSUE TITLE
Insurancefund = Liquidator?

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#84]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/b9b5c4cd9f4c1a9f178ace255df322b77d8eee48/test/foundry/InsuranceFunds.sol#L11

What is the difference between this file and the liquidation file?

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/b9b5c4cd9f4c1a9f178ace255df322b77d8eee48/test/foundry/InsuranceFunds.sol#L101-L102

For tesing insurance funds, first, we need to liquidate users to receive 10% insurance funds from their collateral
