### ISSUE TITLE
Upper bound is bit high

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#85]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/09a4d83c861e2f154a3abe2dbf520b77700dd54c/contracts/Exchange.sol#L200

Upper bound is 5%, let's set this to 1%, because I do not expect to ever go ever this and a hacker could set this to 5% and 
hold the contract hostage for a significant amount.

**Comment by Morteza3123** [comment]
https://github.com/nexlabs22/Nex-Dex-Contracts/blob/b0aeeda34f7f400cc5606f47f5654499987957c8/contracts/Exchange.sol#L205-L212
