### ISSUE TITLE
fundingFee calculation missed 1/24

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#9]
uint256 fundingFee = assetSize * (indexPrice - oraclePrice);
->    uint256 fundingFee = assetSize * (indexPrice - oraclePrice) * (1/24)
Every hour I would like 1/24 of the difference to be adjusted.
It is to limit the amount of funding payment that a thrown back and forward between users. 
 Every hour 1/24 of the difference is adjusted, so after a day of funding rates the Nexlabs index price approaches the oracle price.

**Comment by Morteza3123** [comment]
Solved.

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/e88a1cabd055488e39b856cb57ddb5c43e7a8c4d/contracts/Exchange.sol#L492

https://github.com/nexlabs22/Nex-Dex-Contracts/blob/e88a1cabd055488e39b856cb57ddb5c43e7a8c4d/contracts/Exchange.sol#L497

**Comment by Waltermelon-lang** [comment]
I like this response type with the coding inline changes.
