### ISSUE TITLE
Chainlink vrf 

### ISSUE THREAD

**Issue by Waltermelon-lang** [nexlabs22/NEX-Dex-contracts#92]
Add random number generator to generate liquidation order 
Offchain list ordering?
Use part of the random number and use a counter to check. 
How about normal order book ordering? 
Check polygon mainnet costs

**Comment by Morteza3123** [comment]
As I know Chainlink vrf is for random data, can you tell me how we can use it for off-chain ordering?


Onchain order book can be a way but we need to do searching offchain like:

We store orders on-chain and for matching, we search  and get the index of match orders using the backend and pass the index of match orders as input of smart contract function so we don't need to loop too search and pay data

**Comment by Waltermelon-lang** [comment]
-  can you tell me how we can use it for off-chain ordering? 
I thought I may be cheaper to fetch the user list, fetch the random number from chainlink, then go offchain and re-order the list based on these two variables and then return the ordered list to the smart contract. 
The plan is vague and possible nonsense though.

**Comment by Morteza3123** [comment]
It may have some interesting points so I consider chainlink vrf
